[package]
name = "axum-ap"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
httpc-test = "0.1.9"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
anyhow = "1.0.80"

